namespace Assets.Scripts.Craiel.GDX.AI.Sharp.Enums
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public static class EnumValues
    {
        // -------------------------------------------------------------------
        // Auto Generated by EnumValues.tt DO NOT MODIFY DIRECTLY!
        // -------------------------------------------------------------------
        public static readonly IList<BTTaskStatus> BTTaskStatusValues = Enum.GetValues(typeof(BTTaskStatus)).Cast<BTTaskStatus>().ToList();

        public static readonly IList<ReturnReceiptStatus> ReturnReceiptStatusValues = Enum.GetValues(typeof(ReturnReceiptStatus)).Cast<ReturnReceiptStatus>().ToList();

        public static readonly IList<YamlContainerType> YamlContainerTypeValues = Enum.GetValues(typeof(YamlContainerType)).Cast<YamlContainerType>().ToList();

    }
}
